In [1]:
import time
import sys
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split, KFold
import multiprocessing
import os
from tqdm import tqdm
from scipy import sparse

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
from scipy.stats import spearmanr, pearsonr
from sklearn import ensemble

In [3]:
import datetime as dt
from datetime import date
import calendar
from calendar import weekday, day_name

In [4]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import scipy as sp

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [5]:
from patsy import dmatrix
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import scipy as sp
from sklearn.datasets import make_regression

In [6]:
def get_holidays(fpath):
    
    f = open(fpath)
    lines = f.readlines()
    lines = [line.split(" ")[:3] for line in lines]
    lines = ["{} {} {}".format(line[0], line[1], line[2]) for line in lines]
    lines = pd.to_datetime(lines)
    return pd.DataFrame({"date2":lines})

In [7]:
def get_holiday_names(fpath):
    # holiday_names are holidays + around Black Fridays
    
    f = open(fpath)
    lines = f.readlines()
    lines = [line.strip().split(" ")[:4] for line in lines]
    lines_dt = ["{} {} {}".format(line[0], line[1], line[2]) for line in lines]
    lines_dt = pd.to_datetime(lines_dt)
    lines_hol = [line[3] for line in lines]
    return pd.DataFrame({"date2":lines_dt, "holiday_name":lines_hol})

In [8]:
def preprocess(_df):
    
    df = _df.copy()
    
    # date
    df['date2'] = pd.to_datetime(df['date'])
    
    # weekday
    df['weekday'] = df[['date2']].apply(lambda x: dt.datetime.strftime(x['date2'], '%a'), axis=1)
    # 김태형) 더미변수로 바꿔주기 위해 문자열로 생성

    #df['weekday'] = df.date2.dt.weekday
    df['is_weekend'] = df.date2.dt.weekday.isin([5,6])
    df['is_holiday'] = df.date2.isin(holidays.date2)
    df['is_holiday_weekday'] = df.is_holiday & (df.is_weekend == False)
    df['is_holiday_weekend'] = df.is_holiday &  df.is_weekend

    # bool to int (maybe no meaning)
    df.is_weekend = np.where(df.is_weekend, 1, 0)
    df.is_holiday = np.where(df.is_holiday, 1, 0)
    df.is_holiday_weekday = np.where(df.is_holiday_weekday, 1, 0)
    df.is_holiday_weekend = np.where(df.is_holiday_weekend, 1, 0)
    
    # day, month, year
    df['day'] = df.date2.dt.day
    df['month'] = df.date2.dt.month
    df['year'] = df.date2.dt.year
    
    # around BlackFriday
    df = pd.merge(df, holiday_names, on='date2', how = 'left')
    df.loc[df.holiday_name.isnull(), "holiday_name"] = None

    around_BlackFriday = ["BlackFridayM3", "BlackFridayM2", "ThanksgivingDay", "BlackFriday",
                          "BlackFriday1", "BlackFriday2", "BlackFriday3"]
    df["around_BlackFriday"] = np.where(df.holiday_name.isin(around_BlackFriday), 
                                        df.holiday_name, "Else")

    return df

In [9]:
train_file = pd.read_csv("Data/train.csv", sep=',')
train_file

FileNotFoundError: File b'Data/train.csv' does not exist

In [10]:
train_file = preprocess(train_file)
train_file

NameError: name 'train_file' is not defined

In [11]:
key_file = pd.read_csv("Data/key.csv", sep=',')
key_file

FileNotFoundError: File b'Data/key.csv' does not exist

In [12]:
holidays = get_holidays("holidays.txt")
holiday_names = get_holiday_names("holiday_names.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'holidays.txt'

In [44]:
holidays

        date2
0  2012-01-01
1  2012-01-02
2  2012-01-16
3  2012-02-14
4  2012-02-20
5  2012-04-08
6  2012-05-13
7  2012-05-28
8  2012-06-17
9  2012-07-04
10 2012-09-03
11 2012-10-08
12 2012-10-31
13 2012-11-06
14 2012-11-11
15 2012-11-12
16 2012-11-22
17 2012-12-24
18 2012-12-25
19 2012-12-31
20 2013-01-01
21 2013-01-21
22 2013-02-14
23 2013-02-18
24 2013-03-31
25 2013-05-12
26 2013-05-27
27 2013-06-16
28 2013-07-04
29 2013-09-02
30 2013-10-14
31 2013-10-31
32 2013-11-11
33 2013-11-28
34 2013-12-24
35 2013-12-25
36 2013-12-31
37 2014-01-01
38 2014-01-20
39 2014-02-14
40 2014-02-17
41 2014-04-13
42 2014-04-20
43 2014-05-11
44 2014-05-26
45 2014-06-15
46 2014-07-04
47 2014-09-01
48 2014-10-13
49 2014-10-31
50 2014-11-11
51 2014-11-27
52 2014-12-24
53 2014-12-25
54 2014-12-31

In [45]:
holiday_names

        date2         holiday_name
0  2012-01-01          NewYearsDay
1  2012-01-16  MartinLutherKingDay
2  2012-02-14        ValentinesDay
3  2012-02-20        PresidentsDay
4  2012-04-08         EasterSunday
5  2012-05-13           MothersDay
6  2012-05-28          MemorialDay
7  2012-06-17           FathersDay
8  2012-07-04      IndependenceDay
9  2012-09-03             LaborDay
10 2012-10-08          ColumbusDay
11 2012-10-31            Halloween
12 2012-11-11          VeteransDay
13 2012-11-20        BlackFridayM3
14 2012-11-21        BlackFridayM2
15 2012-11-22      ThanksgivingDay
16 2012-11-23          BlackFriday
17 2012-11-24         BlackFriday1
18 2012-11-25         BlackFriday2
19 2012-11-26         BlackFriday3
20 2012-12-24         ChristmasEve
21 2012-12-25         ChristmasDay
22 2012-12-31          NewYearsEve
23 2013-01-01          NewYearsDay
24 2013-01-21  MartinLutherKingDay
25 2013-02-14        ValentinesDay
26 2013-02-18        PresidentsDay
27 2013-03-31         EasterSunday
28 2013-05-12           MothersDay
29 2013-05-27          MemorialDay
30 2013-06-16           FathersDay
31 2013-07-04      IndependenceDay
32 2013-09-02             LaborDay
33 2013-10-14          ColumbusDay
34 2013-10-31            Halloween
35 2013-11-11          VeteransDay
36 2013-11-26        BlackFridayM3
37 2013-11-27        BlackFridayM2
38 2013-11-28      ThanksgivingDay
39 2013-11-29          BlackFriday
40 2013-11-30         BlackFriday1
41 2013-12-01         BlackFriday2
42 2013-12-02         BlackFriday3
43 2013-12-24         ChristmasEve
44 2013-12-25         ChristmasDay
45 2013-12-31          NewYearsEve
46 2014-01-01          NewYearsDay
47 2014-01-20  MartinLutherKingDay
48 2014-02-14        ValentinesDay
49 2014-02-17        PresidentsDay
50 2014-04-20         EasterSunday
51 2014-05-11           MothersDay
52 2014-05-26          MemorialDay
53 2014-06-15           FathersDay
54 2014-07-04      IndependenceDay
55 2014-09-01             LaborDay
56 2014-10-13          ColumbusDay
57 2014-10-31            Halloween

In [52]:
result = pd.merge(train_file, key_file, left_on='store_nbr', right_on='store_nbr', how='outer')
result

,date,store_nbr,item_nbr,units,date2,weekday,is_weekend,is_holiday,is_holiday_weekday,is_holiday_weekend,day,month,year,holiday_name,around_BlackFriday,station_nbr
0,2012-01-01,1,1,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
1,2012-01-01,1,2,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
2,2012-01-01,1,3,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
3,2012-01-01,1,4,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
4,2012-01-01,1,5,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
5,2012-01-01,1,6,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
6,2012-01-01,1,7,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
7,2012-01-01,1,8,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
8,2012-01-01,1,9,29,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
9,2012-01-01,1,10,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
10,2012-01-01,1,11,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
11,2012-01-01,1,12,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
12,2012-01-01,1,13,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
13,2012-01-01,1,14,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
14,2012-01-01,1,15,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
15,2012-01-01,1,16,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
16,2012-01-01,1,17,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
17,2012-01-01,1,18,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
18,2012-01-01,1,19,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
19,2012-01-01,1,20,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
20,2012-01-01,1,21,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
21,2012-01-01,1,22,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
22,2012-01-01,1,23,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
23,2012-01-01,1,24,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
24,2012-01-01,1,25,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
25,2012-01-01,1,26,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
26,2012-01-01,1,27,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
27,2012-01-01,1,28,2,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
28,2012-01-01,1,29,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
29,2012-01-01,1,30,0,2012-01-01,Sun,1,1,0,1,1,1,2012,NewYearsDay,Else,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4617570,2014-10-31,35,82,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617571,2014-10-31,35,83,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617572,2014-10-31,35,84,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617573,2014-10-31,35,85,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617574,2014-10-31,35,86,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617575,2014-10-31,35,87,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617576,2014-10-31,35,88,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617577,2014-10-31,35,89,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617578,2014-10-31,35,90,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617579,2014-10-31,35,91,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617580,2014-10-31,35,92,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617581,2014-10-31,35,93,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617582,2014-10-31,35,94,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617583,2014-10-31,35,95,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617584,2014-10-31,35,96,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617585,2014-10-31,35,97,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617586,2014-10-31,35,98,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617587,2014-10-31,35,99,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617588,2014-10-31,35,100,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617589,2014-10-31,35,101,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617590,2014-10-31,35,102,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617591,2014-10-31,35,103,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617592,2014-10-31,35,104,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617593,2014-10-31,35,105,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617594,2014-10-31,35,106,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617595,2014-10-31,35,107,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617596,2014-10-31,35,108,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617597,2014-10-31,35,109,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617598,2014-10-31,35,110,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5
4617599,2014-10-31,35,111,0,2014-10-31,Fri,0,1,1,0,31,10,2014,Halloween,Else,5

In [16]:
holidays = pd.read_csv('holidays.csv', sep=',')
holidays

          date        day         holiday_name
0   2012-01-01     Sunday          NewYearsDay
1   2012-01-16     Monday  MartinLutherKingDay
2   2012-02-14    Tuesday        ValentinesDay
3   2012-02-20     Monday        PresidentsDay
4   2012-04-08     Sunday         EasterSunday
5   2012-05-13     Sunday           MothersDay
6   2012-05-28     Monday          MemorialDay
7   2012-06-17     Sunday           FathersDay
8   2012-07-04  Wednesday      IndependenceDay
9   2012-09-03     Monday             LaborDay
10  2012-10-08     Monday          ColumbusDay
11  2012-10-31  Wednesday            Halloween
12  2012-11-11     Sunday          VeteransDay
13  2012-11-22   Thursday      ThanksgivingDay
14  2012-12-24     Monday         ChristmasEve
15  2012-12-25    Tuesday         ChristmasDay
16  2012-12-31     Monday          NewYearsEve
17  2013-01-01    Tuesday          NewYearsDay
18  2013-01-21     Monday  MartinLutherKingDay
19  2013-02-14   Thursday        ValentinesDay
20  2013-02-18     Monday        PresidentsDay
21  2013-03-31     Sunday         EasterSunday
22  2013-05-12     Sunday           MothersDay
23  2013-05-27     Monday          MemorialDay
24  2013-06-16     Sunday           FathersDay
25  2013-07-04   Thursday      IndependenceDay
26  2013-09-02     Monday             LaborDay
27  2013-10-14     Monday          ColumbusDay
28  2013-10-31   Thursday            Halloween
29  2013-11-11     Monday          VeteransDay
30  2013-11-28   Thursday      ThanksgivingDay
31  2013-12-24    Tuesday         ChristmasEve
32  2013-12-25  Wednesday         ChristmasDay
33  2013-12-31    Tuesday          NewYearsEve
34  2014-01-01  Wednesday          NewYearsDay
35  2014-01-20     Monday  MartinLutherKingDay
36  2014-02-14     Friday        ValentinesDay
37  2014-02-17     Monday        PresidentsDay
38  2014-04-20     Sunday         EasterSunday
39  2014-05-11     Sunday           MothersDay
40  2014-05-26     Monday          MemorialDay
41  2014-06-15     Sunday           FathersDay
42  2014-07-04     Friday      IndependenceDay
43  2014-09-01     Monday             LaborDay
44  2014-10-13     Monday          ColumbusDay
45  2014-10-31     Friday            Halloween

In [12]:
weather_file = pd.read_csv("weather_processed.csv", sep = ',')
#weather_file['date'] = pd.to_datetime(weather_file['date'], errors='coerce')
weather_file

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed
0,1,2012-01-01,52.0,31.0,42.0,16.0,36.0,40.0,23.0,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
1,2,2012-01-01,48.0,33.0,41.0,16.0,37.0,39.0,24.0,0.0,716.0,1626.0,0.0,0.07,28.82,29.91,9.1,23.0,11.3
2,3,2012-01-01,55.0,34.0,45.0,9.0,24.0,36.0,20.0,0.0,735.0,1720.0,0.0,0.00,29.77,30.47,9.9,31.0,10.0
3,4,2012-01-01,63.0,47.0,55.0,4.0,28.0,43.0,10.0,0.0,728.0,1742.0,0.0,0.00,29.79,30.48,8.0,35.0,8.2
4,6,2012-01-01,63.0,34.0,49.0,0.0,31.0,43.0,16.0,0.0,727.0,1742.0,0.0,0.00,29.95,30.47,14.0,36.0,13.8
5,7,2012-01-01,50.0,33.0,42.0,0.0,26.0,35.0,23.0,0.0,727.0,1742.0,0.0,0.00,29.15,30.54,10.3,32.0,10.2
6,8,2012-01-01,66.0,45.0,42.0,0.0,34.0,46.0,23.0,0.0,727.0,1742.0,0.0,0.00,30.05,30.54,11.0,36.0,10.9
7,9,2012-01-01,34.0,19.0,27.0,0.0,17.0,23.0,38.0,0.0,727.0,1742.0,0.0,0.00,29.34,30.09,22.8,30.0,22.5
8,10,2012-01-01,73.0,53.0,63.0,0.0,55.0,58.0,2.0,0.0,723.0,1738.0,0.0,0.00,30.16,30.19,5.1,24.0,5.5
9,11,2012-01-01,72.0,48.0,60.0,7.0,54.0,56.0,5.0,0.0,724.0,1737.0,0.0,0.00,30.15,30.18,4.6,23.0,4.8
10,12,2012-01-01,72.0,48.0,60.0,7.0,54.0,57.0,5.0,0.0,724.0,1737.0,0.0,0.00,30.15,30.19,4.4,25.0,4.8
11,13,2012-01-01,38.0,18.0,28.0,7.0,12.0,21.0,37.0,0.0,724.0,1737.0,0.0,0.00,24.60,30.59,2.5,16.0,6.1
12,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,739.0,1729.0,0.0,0.00,29.13,30.52,11.4,32.0,11.3
13,15,2012-01-01,48.0,26.0,37.0,16.0,35.0,38.0,28.0,0.0,718.0,1621.0,0.0,0.09,29.53,29.89,2.5,17.0,3.8
14,16,2012-01-01,50.0,30.0,40.0,16.0,37.0,40.0,25.0,0.0,718.0,1621.0,0.0,0.09,29.80,29.89,4.2,21.0,6.8
15,17,2012-01-01,56.0,38.0,47.0,16.0,23.0,37.0,18.0,0.0,718.0,1621.0,0.0,0.00,29.83,30.50,5.4,32.0,5.8
16,18,2012-01-01,59.0,40.0,50.0,4.0,28.0,40.0,15.0,0.0,730.0,1732.0,0.0,0.00,29.98,30.49,9.0,33.0,8.9
17,19,2012-01-01,38.0,25.0,32.0,10.0,26.0,30.0,33.0,0.0,723.0,1628.0,0.5,0.12,29.06,29.79,14.6,29.0,15.6
18,20,2012-01-01,59.0,41.0,50.0,10.0,28.0,40.0,15.0,0.0,723.0,1628.0,0.0,0.00,29.78,30.48,10.9,33.0,10.8
19,1,2012-01-02,50.0,31.0,41.0,10.0,26.0,35.0,24.0,0.0,723.0,1628.0,0.0,0.01,29.44,29.62,9.8,24.0,10.3
20,2,2012-01-02,46.0,28.0,37.0,12.0,24.0,32.0,28.0,0.0,716.0,1627.0,0.0,0.01,28.51,29.62,12.7,26.0,13.3
21,3,2012-01-02,45.0,24.0,35.0,-1.0,11.0,28.0,30.0,0.0,735.0,1721.0,0.0,0.00,29.89,30.63,7.7,32.0,8.2
22,4,2012-01-02,60.0,37.0,49.0,-2.0,26.0,39.0,16.0,0.0,728.0,1742.0,0.0,0.00,29.93,30.64,3.7,36.0,4.8
23,6,2012-01-02,60.0,30.0,45.0,-4.0,27.0,38.0,20.0,0.0,727.0,1742.0,0.0,0.00,30.09,30.63,9.0,1.0,9.3
24,7,2012-01-02,44.0,26.0,35.0,-4.0,17.0,29.0,30.0,0.0,727.0,1742.0,0.0,0.00,29.23,30.66,5.7,34.0,6.9
25,8,2012-01-02,59.0,36.0,35.0,-4.0,29.0,40.0,30.0,0.0,727.0,1742.0,0.0,0.00,30.25,30.66,6.2,36.0,6.7
26,9,2012-01-02,21.0,11.0,16.0,-4.0,8.0,15.0,49.0,0.0,727.0,1742.0,0.0,0.00,29.67,30.44,14.4,32.0,14.7
27,10,2012-01-02,65.0,45.0,55.0,-4.0,33.0,46.0,10.0,0.0,723.0,1738.0,0.0,0.00,30.11,30.14,10.2,30.0,11.2
28,11,2012-01-02,63.0,40.0,52.0,-1.0,31.0,44.0,13.0,0.0,724.0,1738.0,0.0,0.00,30.10,30.14,10.2,29.0,11.1
29,12,2012-01-02,65.0,47.0,56.0,-1.0,33.0,46.0,9.0,0.0,724.0,1738.0,0.0,0.00,30.09,30.14,11.7,30.0,12.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20487,11,2014-10-30,81.0,59.0,70.0,4.0,63.0,65.0,0.0,5.0,640.0,1741.0,0.0,0.00,29.91,29.94,1.6,36.0,3.4
20488,12,2014-10-30,81.0,61.0,71.0,4.0,63.0,66.0,0.0,6.0,640.0,1741.0,0.0,0.09,29.90,29.94,1.5,1.0,3.3
20489,13,2014-10-30,61.0,32.0,47.0,4.0,26.0,38.0,18.0,0.0,640.0,1741.0,0.0,0.00,24.51,30.31,4.8,13.0,6.7
20490,14,2014-10-30,77.0,45.0,61.0,5.0,39.0,50.0,4.0,0.0,650.0,1738.0,0.0,0.00,28.76,30.13,4.4,34.0,10.4
20491,15,2014-10-30,56.0,30.0,43.0,0.0,36.0,39.0,22.0,0.0,618.0,1641.0,0.0,0.00,29.54,29.94,1.7,31.0,2.7
20492,16,2014-10-30,57.0,34.0,46.0,0.0,39.0,43.0,19.0,0.0,618.0,1641.0,0.0,0.00,29.79,29.91,4.0,30.0,4.6
20493,17,2014-10-30,77.0,43.0,60.0,0.0,41.0,50.0,5.0,0.0,618.0,1641.0,0.0,0.00,29.45,30.14,2.6,32.0,5.1
20494,18,2014-10-30,79.0,56.0,68.0,5.0,51.0,58.0,0.0,3.0,643.0,1739.0,0.0,0.00,29.60,30.11,2.9,14.0,5.6
20495,19,2014-10-30,51.0,32.0,42.0,-4.0,33.0,40.0,23.0,0.0,623.0,1647.0,0.0,0.00,29.31,30.08,5.5,27.0,6.0
20496,20,2014-10-30,80.0,52.0,66.0,-4.0,50.0,57.0,0.0,1.0,623.0,1647.0,0.0,0.00,29.40,30.11,1.6,14.0,4.9
20497,1,2014-10-31,53.0,40.0,47.0,-4.0,36.0,41.0,18.0,0.0,623.0,1647.0,0.0,0.00,29.87,30.03,5.4,4.0,5.8
20498,2,2014-10-31,49.0,40.0,45.0,0.0,35.0,40.0,20.0,0.0,619.0,1643.0,0.0,0.00,28.90,30.00,6.2,5.0,7.0
20499,3,2014-10-31,55.0,33.0,44.0,-12.0,32.0,41.0,21.0,0.0,645.0,1729.0,0.0,0.00,29.65,30.36,11.1,35.0,11.5
20500,4,2014-10-31,76.0,56.0,66.0,-1.0,47.0,56.0,0.0,1.0,644.0,1745.0,0.0,0.30,29.55,30.23,6.0,1.0,6.5
20501,5,2014-10-31,76.0,56.0,66.0,-1.0,37.0,56.0,0.0,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
20502,6,2014-10-31,76.0,51.0,64.0,0.0,47.0,55.0,1.0,0.0,644.0,1745.0,0.0,0.17,29.72,30.22,11.3,36.0,11.7
20503,7,2014-10-31,58.0,38.0,48.0,0.0,32.0,41.0,17.0,0.0,644.0,1745.0,0.0,0.00,29.00,30.37,11.0,1.0,11.6
20504,8,2014-10-31,78.0,55.0,67.0,0.0,32.0,41.0,0.0,2.0,644.0,1745.0,0.0,0.00,29.82,30.37,11.0,1.0,5.1
20505,9,2014-10-31,39.0,25.0,32.0,0.0,18.0,27.0,33.0,0.0,644.0,1745.0,0.0,0.00,29.74,30.52,8.3,36.0,8.7
20506,10,2014-10-31,77.0,63.0,70.0,0.0,51.0,59.0,0.0,5.0,640.0,1741.0,0.0,0.00,29.82,29.84,6.9,31.0,7.8
20507,11,2014-10-31,75.0,50.0,63.0,-2.0,53.0,57.0,2.0,0.0,640.0,1740.0,0.0,0.00,29.82,29.85,5.3,30.0,6.1
20508,12,2014-10-31,75.0,60.0,68.0,-2.0,53.0,59.0,0.0,3.0,640.0,1740.0,0.0,0.00,29.80,29.85,7.0,32.0,7.5
20509,13,2014-10-31,58.0,35.0,47.0,-2.0,28.0,37.0,18.0,0.0,640.0,1740.0,0.0,0.00,24.36,30.18,6.1,17.0,7.2
20510,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,651.0,1737.0,0.0,0.00,28.98,30.36,11.9,1.0,12.5
20511,15,2014-10-31,50.0,32.0,41.0,-2.0,34.0,38.0,24.0,0.0,619.0,1640.0,0.0,0.00,29.65,30.03,0.3,3.0,0.6
20512,16,2014-10-31,53.0,34.0,44.0,-2.0,35.0,41.0,21.0,0.0,619.0,1640.0,0.0,0.00,29.90,29.99,4.5,3.0,5.3
20513,17,2014-10-31,59.0,34.0,47.0,-2.0,32.0,41.0,18.0,0.0,619.0,1640.0,0.0,0.00,29.72,30.39,9.2,1.0,9.3
20514,18,2014-10-31,67.0,49.0,58.0,-4.0,40.0,50.0,7.0,0.0,644.0,1738.0,0.0,0.00,29.78,30.28,10.6,36.0,11.2
20515,19,2014-10-31,45.0,33.0,39.0,-6.0,24.0,32.0,26.0,0.0,624.0,1646.0,0.1,0.02,29.51,30.24,20.4,34.0,20.9
20516,20,2014-10-31,68.0,50.0,59.0,-6.0,39.0,50.0,6.0,0.0,624.0,1646.0,0.0,0.00,29.57,30.27,10.5,36.0,11.2

In [11]:
tmp_weather_file = pd.read_csv("weather.csv", sep = ',')
tmp_weather_file

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,codesum,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed
0,1,2012-01-01,52,31,42,M,36,40,23,0,-,-,RA FZFG BR,M,0.05,29.78,29.92,3.6,20,4.6
1,2,2012-01-01,48,33,41,16,37,39,24,0,0716,1626,RA,0.0,0.07,28.82,29.91,9.1,23,11.3
2,3,2012-01-01,55,34,45,9,24,36,20,0,0735,1720,,0.0,0.00,29.77,30.47,9.9,31,10.0
3,4,2012-01-01,63,47,55,4,28,43,10,0,0728,1742,,0.0,0.00,29.79,30.48,8.0,35,8.2
4,6,2012-01-01,63,34,49,0,31,43,16,0,0727,1742,,0.0,0.00,29.95,30.47,14.0,36,13.8
5,7,2012-01-01,50,33,42,M,26,35,23,0,-,-,,0.0,0.00,29.15,30.54,10.3,32,10.2
6,8,2012-01-01,66,45,M,M,34,46,M,M,-,-,RA BR,M,0.00,30.05,M,11.0,36,10.9
7,9,2012-01-01,34,19,27,M,17,23,38,0,-,-,UP,M,T,29.34,30.09,22.8,30,22.5
8,10,2012-01-01,73,53,63,M,55,58,2,0,0723,1738,FG+ FG BR,M,0.00,30.16,30.19,5.1,24,5.5
9,11,2012-01-01,72,48,60,7,54,56,5,0,0724,1737,FG+ FG BR,0.0,0.00,30.15,30.18,4.6,23,4.8
10,12,2012-01-01,72,48,60,M,54,57,5,0,-,-,FG+ FG BR,0.0,0.00,30.15,30.19,4.4,25,4.8
11,13,2012-01-01,38,18,28,M,12,21,37,0,-,-,,M,0.00,24.60,30.59,2.5,16,6.1
12,14,2012-01-01,50,34,42,5,25,35,23,0,0739,1729,,0.0,0.00,29.13,30.52,11.4,32,11.3
13,15,2012-01-01,48,26,37,16,35,38,28,0,0718,1621,RA FG+ FZFG BR,0.0,0.09,29.53,29.89,2.5,17,3.8
14,16,2012-01-01,50,30,40,M,37,40,25,0,-,-,RA MIFG BR,M,T,29.80,29.89,4.2,21,6.8
15,17,2012-01-01,56,38,47,M,23,37,18,0,-,-,,0.0,0.00,29.83,30.50,5.4,32,5.8
16,18,2012-01-01,59,40,50,4,28,40,15,0,0730,1732,,0.0,0.00,29.98,30.49,9.0,33,8.9
17,19,2012-01-01,38,25,32,10,26,30,33,0,0723,1628,RA SN BR,0.5,0.12,29.06,29.79,14.6,29,15.6
18,20,2012-01-01,59,41,50,M,28,40,15,0,-,-,,0.0,0.00,29.78,30.48,10.9,33,10.8
19,1,2012-01-02,50,31,41,M,26,35,24,0,-,-,,M,0.01,29.44,29.62,9.8,24,10.3
20,2,2012-01-02,46,28,37,12,24,32,28,0,0716,1627,,T,0.01,28.51,29.62,12.7,26,13.3
21,3,2012-01-02,45,24,35,-1,11,28,30,0,0735,1721,,0.0,0.00,29.89,30.63,7.7,32,8.2
22,4,2012-01-02,60,37,49,-2,26,39,16,0,0728,1742,,0.0,0.00,29.93,30.64,3.7,36,4.8
23,6,2012-01-02,60,30,45,-4,27,38,20,0,0727,1742,,0.0,0.00,30.09,30.63,9.0,01,9.3
24,7,2012-01-02,44,26,35,M,17,29,30,0,-,-,,0.0,0.00,29.23,30.66,5.7,34,6.9
25,8,2012-01-02,59,36,M,M,29,40,M,M,-,-,,M,0.00,30.25,M,6.2,36,6.7
26,9,2012-01-02,21,11,16,M,8,15,49,0,-,-,SN UP,M,T,29.67,30.44,14.4,32,14.7
27,10,2012-01-02,65,45,55,M,33,46,10,0,0723,1738,,M,0.00,30.11,30.14,10.2,30,11.2
28,11,2012-01-02,63,40,52,-1,31,44,13,0,0724,1738,,0.0,0.00,30.10,30.14,10.2,29,11.1
29,12,2012-01-02,65,47,56,M,33,46,9,0,-,-,,0.0,0.00,30.09,30.14,11.7,30,12.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20487,11,2014-10-30,81,59,70,4,63,65,0,5,0640,1741,TS BR,0.0,0.00,29.91,29.94,1.6,36,3.4
20488,12,2014-10-30,81,61,71,M,63,66,0,6,-,-,TSRA BR,0.0,0.09,29.90,29.94,1.5,01,3.3
20489,13,2014-10-30,61,32,47,M,26,38,18,0,-,-,,M,0.00,24.51,30.31,4.8,13,6.7
20490,14,2014-10-30,77,45,61,5,39,50,4,0,0650,1738,,0.0,0.00,28.76,30.13,4.4,34,10.4
20491,15,2014-10-30,56,30,43,0,36,39,22,0,0618,1641,FG BR,0.0,T,29.54,29.94,1.7,31,2.7
20492,16,2014-10-30,57,34,46,M,39,43,19,0,-,-,,M,0.00,29.79,29.91,4.0,30,4.6
20493,17,2014-10-30,77,43,60,M,41,50,5,0,-,-,,0.0,0.00,29.45,30.14,2.6,32,5.1
20494,18,2014-10-30,79,56,68,5,51,58,0,3,0643,1739,RA,0.0,T,29.60,30.11,2.9,14,5.6
20495,19,2014-10-30,51,32,42,-4,33,40,23,0,0623,1647,RA,0.0,T,29.31,30.08,5.5,27,6.0
20496,20,2014-10-30,80,52,66,M,50,57,0,1,-,-,,0.0,0.00,29.40,30.11,1.6,14,4.9
20497,1,2014-10-31,53,40,47,M,36,41,18,0,-,-,,M,0.00,29.87,30.03,5.4,04,5.8
20498,2,2014-10-31,49,40,45,0,35,40,20,0,0619,1643,,0.0,0.00,28.90,30.00,6.2,05,7.0
20499,3,2014-10-31,55,33,44,-12,32,41,21,0,0645,1729,,0.0,0.00,29.65,30.36,11.1,35,11.5
20500,4,2014-10-31,76,56,66,-1,47,56,0,1,0644,1745,RA BR,0.0,0.30,29.55,30.23,6.0,01,6.5
20501,5,2014-10-31,M,M,M,M,37,M,M,M,0616,1640,,M,M,M,30.01,10.8,05,M
20502,6,2014-10-31,76,51,64,0,47,55,1,0,0644,1745,RA BR,0.0,0.17,29.72,30.22,11.3,36,11.7
20503,7,2014-10-31,58,38,48,M,32,41,17,0,-,-,,0.0,0.00,29.00,30.37,11.0,01,11.6
20504,8,2014-10-31,78,55,67,M,M,M,0,2,-,-,RA,M,T,29.82,M,M,M,5.1
20505,9,2014-10-31,39,25,32,M,18,27,33,0,-,-,,M,0.00,29.74,30.52,8.3,36,8.7
20506,10,2014-10-31,77,63,70,M,51,59,0,5,0640,1741,,M,0.00,29.82,29.84,6.9,31,7.8
20507,11,2014-10-31,75,50,63,-2,53,57,2,0,0640,1740,,0.0,0.00,29.82,29.85,5.3,30,6.1
20508,12,2014-10-31,75,60,68,M,53,59,0,3,-,-,BR,0.0,0.00,29.80,29.85,7.0,32,7.5
20509,13,2014-10-31,58,35,47,M,28,37,18,0,-,-,,M,0.00,24.36,30.18,6.1,17,7.2
20510,14,2014-10-31,60,38,49,-7,31,42,16,0,0651,1737,,0.0,0.00,28.98,30.36,11.9,01,12.5
20511,15,2014-10-31,50,32,41,-2,34,38,24,0,0619,1640,,0.0,0.00,29.65,30.03,0.3,03,0.6
20512,16,2014-10-31,53,34,44,M,35,41,21,0,-,-,,M,0.00,29.90,29.99,4.5,03,5.3
20513,17,2014-10-31,59,34,47,M,32,41,18,0,-,-,RA,0.0,0.00,29.72,30.39,9.2,01,9.3
20514,18,2014-10-31,67,49,58,-4,40,50,7,0,0644,1738,,0.0,0.00,29.78,30.28,10.6,36,11.2
20515,19,2014-10-31,45,33,39,-6,24,32,26,0,0624,1646,RA SN,0.1,0.02,29.51,30.24,20.4,34,20.9
20516,20,2014-10-31,68,50,59,M,39,50,6,0,-,-,,0.0,0.00,29.57,30.27,10.5,36,11.2

In [57]:
all_data_result = pd.merge(result, weather_file, on=['date', 'station_nbr'], how='left')
all_data_result

,date,store_nbr,item_nbr,units,date2,weekday,is_weekend,is_holiday,is_holiday_weekday,is_holiday_weekend,...,cool,sunrise,sunset,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed
0,2012-01-01,1,1,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
1,2012-01-01,1,2,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
2,2012-01-01,1,3,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
3,2012-01-01,1,4,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
4,2012-01-01,1,5,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
5,2012-01-01,1,6,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
6,2012-01-01,1,7,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
7,2012-01-01,1,8,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
8,2012-01-01,1,9,29,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
9,2012-01-01,1,10,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
10,2012-01-01,1,11,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
11,2012-01-01,1,12,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
12,2012-01-01,1,13,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
13,2012-01-01,1,14,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
14,2012-01-01,1,15,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
15,2012-01-01,1,16,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
16,2012-01-01,1,17,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
17,2012-01-01,1,18,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
18,2012-01-01,1,19,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
19,2012-01-01,1,20,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
20,2012-01-01,1,21,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
21,2012-01-01,1,22,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
22,2012-01-01,1,23,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
23,2012-01-01,1,24,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
24,2012-01-01,1,25,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
25,2012-01-01,1,26,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
26,2012-01-01,1,27,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
27,2012-01-01,1,28,2,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
28,2012-01-01,1,29,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
29,2012-01-01,1,30,0,2012-01-01,Sun,1,1,0,1,...,0.0,716.0,1626.0,0.0,0.05,29.78,29.92,3.6,20.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4617570,2014-10-31,35,82,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617571,2014-10-31,35,83,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617572,2014-10-31,35,84,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617573,2014-10-31,35,85,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617574,2014-10-31,35,86,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617575,2014-10-31,35,87,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617576,2014-10-31,35,88,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617577,2014-10-31,35,89,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617578,2014-10-31,35,90,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617579,2014-10-31,35,91,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617580,2014-10-31,35,92,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617581,2014-10-31,35,93,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617582,2014-10-31,35,94,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617583,2014-10-31,35,95,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617584,2014-10-31,35,96,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617585,2014-10-31,35,97,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617586,2014-10-31,35,98,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617587,2014-10-31,35,99,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617588,2014-10-31,35,100,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617589,2014-10-31,35,101,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617590,2014-10-31,35,102,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617591,2014-10-31,35,103,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617592,2014-10-31,35,104,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617593,2014-10-31,35,105,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617594,2014-10-31,35,106,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617595,2014-10-31,35,107,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617596,2014-10-31,35,108,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617597,2014-10-31,35,109,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617598,2014-10-31,35,110,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5
4617599,2014-10-31,35,111,0,2014-10-31,Fri,0,1,1,0,...,1.0,616.0,1640.0,0.0,0.30,29.55,30.01,10.8,5.0,6.5

In [58]:
all_data_result.to_csv("another_all_train_matrix.csv", sep=',', index=None)

In [13]:
#여기서 부터
all_data_result = pd.read_csv('another_all_train_matrix.csv', sep=',')

In [14]:
all_data_result['is_weekend'] = all_data_result['is_weekend'].astype(object)
all_data_result['is_holiday'] = all_data_result['is_holiday'].astype(object)
all_data_result['is_holiday_weekday'] = all_data_result['is_holiday_weekday'].astype(object)
all_data_result['is_holiday_weekend'] = all_data_result['is_holiday_weekend'].astype(object)

In [ ]:
# ls_store_nbr = set(all_data_result.store_nbr)
# mod = sys.modules[__name__]
# df = pd.DataFrame()
# for store_nbr in tqdm(ls_store_nbr):
#     #setattr(mod, 'store_{}'.format(store_nbr), all_data_result[all_data_result['store_nbr'] == store_nbr])
#     data = all_data_result[all_data_result['store_nbr'] == store_nbr]
#     mergedata = pd.merge(data, weather_file, on = ['date'])
#     #df = df.append(mergedata, ignore_index=True)
#     setattr(mod, 'store_{}_data'.format(store_nbr), mergedata)
#     #mergedata.to_csv("store_{}_data.csv".format(store_nbr), sep=',', index=None)

 56%|█████▌    | 25/45 [11:46<09:25, 28.26s/it]

In [30]:
def formulaName(df, store):
    result = ""
    _df = df
#     tmpPvalue = _df['P>|t|'].astype(float)
#     tmpdf = _df[tmpPvalue < 0.1]
    tmpdf = _df
    ls = []
    tmp_store_df = tmpdf[tmpdf['store_nbr'] == store]
    Names = tmp_store_df.Name
    i = 0
    for Name in Names:
        i += 1
        if str(Name) != 'nan' and i < len(Names):
            result += Name + " "
        elif str(Name) != 'nan':
            result += Name
    ls.append(result)
    return ls

def store_formulaList(Names):
    ls_result = []
    tmp_ls = Names
    a = ""
    for item in tmp_ls:
        i = 0
        words = item.split(" ")
        for word in words:
            i += 1
            if word.startswith("C(weekday)"):
                if a.find("C(weekday)") == -1:
                    a += "C(weekday) + "
            elif word.startswith("C(item_nbr)"):
                if a.find("C(item_nbr)") == -1:
                    a += "C(item_nbr) + "   
            elif word.startswith("C(holiday_name)"):
                if a.find("C(holiday_name)") == -1:
                    a += "C(holiday_name) + " 
            elif word.startswith("C(around_BlackFriday)"):
                if a.find("C(around_BlackFriday)") == -1:
                    a += "C(around_BlackFriday) + "
            elif word.startswith("C(is_holiday)"):
                if a.find("C(is_holiday)") == -1:
                    a += "C(is_holiday) + "
            elif word.startswith("C(is_holiday_weekday)"):
                if a.find("C(is_holiday_weekday)") == -1:
                    a += "C(is_holiday_weekday) + "
            elif word.startswith("C(is_weekend)"):
                if a.find("C(is_weekend)") == -1:
                    a += "C(is_weekend) + "
            elif word.startswith("C(is_holiday_weekend)"):
                if a.find("C(is_holiday_weekend)") == -1:
                    a += "C(is_holiday_weekend) + "
            else:
                a += word + " + "

    return a[:-3]

def convert_store_formulaList(Names):
    ls_result = []
    tmp_ls = Names
    a = ""
    for item in tmp_ls:
        i = 0
        words = item.split(" ")
        for word in words:
            i += 1
            if word.startswith("C(weekday)"):
                if a.find("C(weekday)") == -1 and a.find("weekday") == -1:
                    a += "weekday + "
            elif word.startswith("C(item_nbr)"):
                if a.find("C(item_nbr)") == -1 and a.find("item_nbr") == -1:
                    a += "item_nbr + "   
            elif word.startswith("C(holiday_name)"):
                if a.find("C(holiday_name)") == -1 and a.find("holiday_name") == -1:
                    a += "holiday_name + "
            elif word.startswith("C(around_BlackFriday)"):
                if a.find("C(around_BlackFriday)") == -1 and a.find("around_BlackFriday") == -1:
                    a += "around_BlackFriday + "
            elif word.startswith("C(is_holiday)"):
                if a.find("C(is_holiday)") == -1 and a.find("is_holiday") == -1:
                    a += "is_holiday + "
            elif word.startswith("C(is_holiday_weekday)"):
                if a.find("C(is_holiday_weekday)") == -1 and a.find("is_holiday_weekday") == -1:
                    a += "is_holiday_weekday + "
            elif word.startswith("C(is_weekend)"):
                if a.find("C(is_weekend)") == -1 and a.find("is_weekend") == -1:
                    a += "is_weekend + "
            elif word.startswith("C(is_holiday_weekend)"):
                if a.find("C(is_holiday_weekend)") == -1 and a.find("is_holiday_weekend") == -1:
                    a += "is_holiday_weekend + "
            else:
                a += word + " + "

    return a[:-3]

def store_test_predict(data, test_data, store, formulaList, f_convertList) :
#     if formulaList == None:
#         model = sm.OLS.from_formula( "np.log1p(units) ~ C(item_nbr) + C(weekday) +"
#                                      "C(is_weekend) + C(is_holiday_weekday) + C(is_holiday) + "
#                                      "C(is_holiday_weekend) + C(holiday_name) + C(around_BlackFriday) + "
#                                      "depart + cool + sunrise + "
#                                      "sunset + snowfall + preciptotal + stnpressure + sealevel + resultspeed + resultdir +"
#                                      "avgspeed", data=result)
#     else:
#         model = sm.OLS.from_formula( "np.log1p(units) ~ " + formulaList , data=data)

    model = sm.OLS.from_formula( "np.log1p(units) ~ C(item_nbr):C(weekday) +"
                                     "C(is_weekend) + C(is_holiday_weekday) + C(is_holiday) +  C(holiday_name) + C(around_BlackFriday)+"
                                     "C(is_holiday_weekend) + "
                                     "depart + cool + sunrise + "
                                     "sunset + snowfall + preciptotal + stnpressure + sealevel + resultspeed + resultdir +"
                                     "avgspeed", data=data)

    result_fit = model.fit()
#     num_attr = ['store_nbr']
#     num_attr.extend(f_convertList)
    num_attr = ['store_nbr', 'item_nbr', 'weekday', 
            'is_weekend', 'is_holiday_weekday', 'holiday_name', 'around_BlackFriday',
            'is_holiday', 'is_holiday_weekend',
            'depart', 'cool',
            'sunrise', 'sunset', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel',
            'resultspeed', 'resultdir', 'avgspeed']    
    try:
        test_predict = test_data[num_attr]
    except:
        test_predict = test_data[num_attr]
    


    result = result_fit.predict(test_predict)
    return result

In [17]:
def store_storage(result, store, formulaList) :
    """
    회귀분석 결과 모음

    전역변수로 아래 데이터 프레임 선언
    result_sets = pd.DataFrame(columns = ["R square", "AIC", "BIC", "P_fstatics", "P_omnibus", "P_jb", "Cond_no"])

    Variables_name.fit() 상태로 삽입
    ex)result = model.fit() 이면
    result를 삽입    


    reason = 이전 데이터 셋에서 무엇을 변화시켰는지 적을 것.
    """    
        
    global result_sets
    result_sets = pd.DataFrame(columns = ["store_nbr", "R square", "F_statics", "Prob(F_statics)", "AIC", "BIC",
                                          "Omnibus", "P_omnibus", "P_jb", "Cond_no"])

#     if formulaList == None:
#         model = sm.OLS.from_formula( "np.log1p(units) ~ C(item_nbr):C(weekday) +"
#                                      "C(is_weekend) + C(is_holiday_weekday) + C(is_holiday) + "
#                                      "C(is_holiday_weekend) + "
#                                      "depart + cool + sunrise + "
#                                      "sunset + snowfall + preciptotal + stnpressure + sealevel + resultspeed + resultdir +"
#                                      "avgspeed", data=result)
#     else:
#         model = sm.OLS.from_formula( "np.log1p(units) ~ " + formulaList , data=result)

    model = sm.OLS.from_formula( "np.log1p(units) ~ C(item_nbr):C(weekday) +"
                                     "C(is_weekend) + C(is_holiday_weekday) + C(is_holiday) +  C(holiday_name) + C(around_BlackFriday)+"
                                     "C(is_holiday_weekend) + "
                                     "depart + cool + sunrise + "
                                     "sunset + snowfall + preciptotal + stnpressure + sealevel + resultspeed + resultdir +"
                                     "avgspeed", data=result)

    result = model.fit()

    summary = result.summary()
    
    t1 = summary.tables[0]
    t2 = summary.tables[1]
    t3 = summary.tables[2]
    
    r_squared = float(t1.data[0][3])
    fstatics = float(t1.data[2][3])
    p_fstatics = float(t1.data[3][3])
    AIC = float(t1.data[5][3])
    BIC = float(t1.data[6][3])
    

    omnibus = float(t3.data[0][3])
    p_omnibus = float(t3.data[1][1])
    p_jb = float(t3.data[2][3])
    con = float(t3.data[3][3])

    put = {
        "store_nbr" : store,
        "R square" : r_squared,
        "F_statics" : fstatics,
        "Prob(F_statics)" : p_fstatics,
        "AIC" : AIC,
        "BIC" : BIC,
        "Omnibus" : omnibus,
        "P_omnibus" : p_omnibus,
        "P_jb" : p_jb,
        "Cond_no" : con,  
    }
    
    result_sets.loc[len(result_sets)] = put
    
    for i in range(2, len(t2)):
        result_sets = result_sets.append({
            "store_nbr" : store,
            "Name" : t2.data[i][0],
            "std err" : t2.data[i][2],
            "t" : t2.data[i][3],
            "P>|t|" : t2.data[i][4],
            "0.025" : t2.data[i][5],
            "0.975" : t2.data[i][6],
        }, ignore_index=True)
 
    return result_sets, result

In [18]:
def item_formulaName(df, item):
    result = ""
    _df = df
    tmpPvalue = _df['P>|t|'].astype(float)
    tmpdf = _df[tmpPvalue < 0.1]
    ls = []
    tmp_item_df = tmpdf[tmpdf['item_nbr'] == item]
    Names = tmp_item_df.Name
    i = 0
    for Name in Names:
        i += 1
        if i < len(Names):
            result += Name + " "
        else:
            result += Name
    ls.append(result)
    return ls

def item_formulaList(Names):
    ls_result = []
    tmp_ls = Names
    a = ""
    for item in tmp_ls:
        i = 0
        words = item.split(" ")
        for word in words:
            i += 1
            if word.startswith("C(weekday)"):
                if a.find("C(weekday)") == -1:
                    a += "C(weekday) + "
            elif word.startswith("C(store_nbr)"):
                if a.find("C(store_nbr)") == -1:
                    a += "C(store_nbr) + "
            else:
                a += word + " + "

    return a[:-3]

In [263]:
def item_storage(result, item, formulaList) :
    """
    회귀분석 결과 모음

    전역변수로 아래 데이터 프레임 선언
    result_sets = pd.DataFrame(columns = ["R square", "AIC", "BIC", "P_fstatics", "P_omnibus", "P_jb", "Cond_no"])

    Variables_name.fit() 상태로 삽입
    ex)result = model.fit() 이면
    result를 삽입    


    reason = 이전 데이터 셋에서 무엇을 변화시켰는지 적을 것.
    """    
    
    global result_sets
    result_sets = pd.DataFrame(columns = ["item_nbr", "R square", "F_statics", "Prob(F_statics)", "AIC", "BIC",
                                          "Omnibus", "P_omnibus", "P_jb", "Cond_no"])
                
    if formulaList == None or formulaList == '':
        model = sm.OLS.from_formula( "units ~ C(store_nbr) + C(weekday):C() +"
                                     "is_weekend + is_holiday_weekday + "
                                     "is_holiday_weekend + "
                                     "tmax + tmin + tavg + depart + dewpoint + wetbulb + heat + cool + sunrise + "
                                     "sunset + snowfall + preciptotal + stnpressure + sealevel + resultspeed + resultdir +"
                                     "avgspeed", data=result)
    else:
        model = sm.OLS.from_formula( "units ~ " + formulaList , data=result)

    result = model.fit()

    summary = result.summary()
    
    t1 = summary.tables[0]
    t2 = summary.tables[1]
    t3 = summary.tables[2]
    
    r_squared = float(t1.data[0][3])
    fstatics = float(t1.data[2][3])
    p_fstatics = float(t1.data[3][3])
    AIC = float(t1.data[5][3])
    BIC = float(t1.data[6][3])
    

    omnibus = float(t3.data[0][3])
    p_omnibus = float(t3.data[1][1])
    p_jb = float(t3.data[2][3])
    con = float(t3.data[3][3])

    put = {
        "item_nbr" : item,
        "R square" : r_squared,
        "F_statics" : fstatics,
        "Prob(F_statics)" : p_fstatics,
        "AIC" : AIC,
        "BIC" : BIC,
        "Omnibus" : omnibus,
        "P_omnibus" : p_omnibus,
        "P_jb" : p_jb,
        "Cond_no" : con,  
    }
    
    result_sets.loc[len(result_sets)] = put
    
    for i in range(2, len(t2)):
        result_sets = result_sets.append({
            "item_nbr" : item,
            "Name" : t2.data[i][0],
            "std err" : t2.data[i][2],
            "t" : t2.data[i][3],
            "P>|t|" : t2.data[i][4],
            "0.025" : t2.data[i][5],
            "0.975" : t2.data[i][6],
        }, ignore_index=True)
 
    return result_sets, result

In [19]:
def convertList(f_name):
    result = f_name.split(" + ")
    return result

In [20]:
def erase_outlier_np(result, data, category=False, dropped=False):
    """
    get the fitted model result, then erase outliers in data,
    by Fox' Outlier Recommendation.
    return arranged data, dropped data(when True)
    """

    influence = result.get_influence()

    if category:
        fox_cr = 4 / (len(data) - result.df_model + 1)
    else:
        fox_cr = 4 / (len(data) - result.df_model)

    cooks_d2, pvals = influence.cooks_distance
    idx = np.where(cooks_d2 > fox_cr)[0]

    dropped_data = data.iloc[idx]
    data = data.drop(data.index[idx])
    data.reset_index(drop=True, inplace=True)

    if dropped:

        return data, dropped_data

    return data

In [ ]:
# model2 = sm.OLS.from_formula("units ~ weekday + is_weekend +"
#                             "is_holiday +is_holiday_weekend + day +"
#                             "year +"
#                             "tmin + tavg  + wetbulb + heat+"
#                             "cool + sunrise + sunset + snowfall + preciptotal + stnpressure+"
#                             "sealevel + resultspeed + resultdir + avgspeed", data=all_data_result)
# result = model2.fit()

# num_attr = ['store_nbr', 'item_nbr', 'weekday', 'is_weekend', 
#             'is_holiday', 'is_holiday_weekend',
#             'day', 'year',
#             'tmin', 'tavg',
#             'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'snowfall',
#             'preciptotal', 'stnpressure', 'sealevel', 'resultspeed',
#             'resultdir', 'avgspeed']

# test_predict = test_gg[num_attr]

# test = result.predict(test_predict)

In [21]:
#store_nbr 기준으로 OLS 분류
ls_store_nbr = set(all_data_result.store_nbr)
df = pd.DataFrame()
df_out = pd.DataFrame()
for store_nbr in tqdm(ls_store_nbr):
    data = all_data_result[all_data_result['store_nbr'] == store_nbr]
    #data = data[data['units'] > 0]
    tmp_df, result = store_storage(data, store_nbr, None)
    df = df.append(tmp_df, ignore_index=True)
    temp = erase_outlier_np(result, data)
    df_out = df_out.append(temp, ignore_index=True)

  0%|          | 0/45 [00:00<?, ?it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:309: RuntimeWarning: invalid value encountered in sqrt
  return  self.results.resid / sigma / np.sqrt(1 - hii)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:309: RuntimeWarning: divide by zero encountered in true_divide
  return  self.results.resid / sigma / np.sqrt(1 - hii)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:403: RuntimeWarning: divide by zero encountered in true_divide
  cooks_d2 *= hii / (1 - hii)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()
100%|██████████| 45/45 [08:40<00:00, 11.57s/it]

In [ ]:
df.to_csv('store_units_OLS_1차_20180314_4.csv', sep=',', index=None)

In [22]:
#2차 _ 아웃라이어 제거
ls_store_nbr = set(all_data_result.store_nbr)
df = pd.DataFrame()
for store_nbr in tqdm(ls_store_nbr):
    data = df_out[df_out['store_nbr'] == store_nbr]
    #data = data[data['units'] > 0]
    tmp_df, result = store_storage(data, store_nbr, None)
    df = df.append(tmp_df, ignore_index=True)

100%|██████████| 45/45 [07:41<00:00, 10.25s/it]

In [ ]:
df.to_csv('store_units_OLS_2차(아웃라이어제거)_20180314_4.csv', sep=',', index=None)

In [33]:
#store_nbr 기준으로 OLS 분류 - p-value 제거
ls_store_nbr = set(all_data_result.store_nbr)
o_df = pd.DataFrame()
test_predict = pd.DataFrame()
for store_nbr in tqdm(ls_store_nbr):
    data = df_out[df_out['store_nbr'] == store_nbr]
    test_data = test_gg[test_gg['store_nbr'] == store_nbr]
    #data = data[data['units'] > 0]
    f_list = formulaName(df, store_nbr)
    f_name = convert_store_formulaList(f_list)
    f_convertList = convertList(f_name)
    tmp_df, result = store_storage(data, store_nbr, f_name)
    result.predict(test_data)
#     tmp_predict = pd.DataFrame(data=store_test_predict(data, test_data, store_nbr, f_name, f_convertList))
#     test_predict = test_predict.append(tmp_predict, ignore_index=True)
#     o_df = o_df.append(tmp_df, ignore_index=True)

  0%|          | 0/45 [00:00<?, ?it/s]
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tqdm/_tqdm.py", line 148, in run
    for instance in self.tqdm_cls._instances:
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration

 64%|██████▍   | 29/45 [05:18<02:55, 10.99s/it]

PatsyError: Error converting data to categorical: observation with value 'ChristmasDay' does not match any of the expected levels (expected: ['BlackFriday', 'BlackFriday1', ..., 'ValentinesDay', 'VeteransDay'])
    np.log1p(units) ~ C(item_nbr):C(weekday) +C(is_weekend) + C(is_holiday_weekday) + C(is_holiday) +  C(holiday_name) + C(around_BlackFriday)+C(is_holiday_weekend) + depart + cool + sunrise + sunset + snowfall + preciptotal + stnpressure + sealevel + resultspeed + resultdir +avgspeed
                                                                                                       ^^^^^^^^^^^^^^^

In [ ]:
test_predict.to_csv('test_predict_20180314_4.csv', sep=',', index=None)

In [368]:
test_predict

               0
0       0.060506
1       0.059777
2       0.059048
3       0.058320
4       0.057591
5       0.056862
6       0.056133
7       0.055405
8       0.054676
9       0.053947
10      0.053218
11      0.052490
12      0.051761
13      0.051032
14      0.050303
15      0.049575
16      0.048846
17      0.048117
18      0.047388
19      0.046660
20      0.045931
21      0.045202
22      0.044473
23      0.043744
24      0.043016
25      0.042287
26      0.041558
27      0.040829
28      0.040101
29      0.039372
...          ...
526887  0.002852
526888  0.002511
526889  0.002170
526890  0.001829
526891  0.001488
526892  0.001146
526893  0.000805
526894  0.000464
526895  0.000123
526896 -0.000218
526897 -0.000559
526898 -0.000901
526899 -0.001242
526900 -0.001583
526901 -0.001924
526902 -0.002265
526903 -0.002606
526904 -0.002948
526905 -0.003289
526906 -0.003630
526907 -0.003971
526908 -0.004312
526909 -0.004653
526910 -0.004995
526911 -0.005336
526912 -0.005677
526913 -0.006018
526914 -0.006359
526915 -0.006700
526916 -0.007042

[526917 rows x 1 columns]

In [228]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  units   R-squared:                       0.197
Model:                            OLS   Adj. R-squared:                  0.196
Method:                 Least Squares   F-statistic:                     598.0
Date:                Wed, 14 Mar 2018   Prob (F-statistic):          2.60e-118
Time:                        15:25:54   Log-Likelihood:                -13669.
No. Observations:                2444   AIC:                         2.734e+04
Df Residuals:                    2442   BIC:                         2.735e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    112.1472      2.324     48.261      0.000     107.590     116.704
item_nbr      -1.2795      0.052    -24.453      0.000      -1.382      -1.177
==============================================================================
Omnibus:                      314.250   Durbin-Watson:                   2.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              461.917
Skew:                           0.940   Prob(JB):                    4.97e-101
Kurtosis:                       4.001   Cond. No.                         78.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## Model_store

In [35]:
8+++++
9+

+*/876`# #store_nbr 기준으로 OLS 분류
# ls_store_nbr = set(all_data_result.store_nbr)
# df = pd.DataFrame()
# df_out = pd.DataFrame()
# for store_nbr in tqdm(ls_store_nbr):
#     data = all_data_result[all_data_result['store_nbr'] == store_nbr]
#     data = data[data['units'] > 0]
#     tmp_df, result = store_storage(data, store_nbr, None)
#     df = df.append(tmp_df, ignore_index=True)
#     temp = erase_outlier_np(result, data)
#     df_out = df_out.append(temp, ignore_index=True)

100%|██████████| 45/45 [00:07<00:00,  5.66it/s]

In [38]:
# df.to_csv('store_units0_OLS_1차.csv', sep=',', index=None)

In [39]:
# #2차 _ 아웃라이어 제거
# ls_store_nbr = set(all_data_result.store_nbr)
# df = pd.DataFrame()
# for store_nbr in tqdm(ls_store_nbr):
#     data = df_out[df_out['store_nbr'] == store_nbr]
#     data = data[data['units'] > 0]
#     tmp_df, result = store_storage(data, store_nbr, None)
#     df = df.append(tmp_df, ignore_index=True)

100%|██████████| 45/45 [00:05<00:00,  7.91it/s]

In [40]:
# df.to_csv('store_units0_OLS_2차(아웃라이어제거).csv', sep=',', index=None)

In [41]:
# #store_nbr 기준으로 OLS 분류 - p-value 제거
# ls_store_nbr = set(all_data_result.store_nbr)
# o_df = pd.DataFrame()
# for store_nbr in tqdm(ls_store_nbr):
#     data = df_out[df_out['store_nbr'] == store_nbr]
#     data = data[data['units'] > 0]
#     f_list = formulaName(df, store_nbr)
#     f_name = formulaList(f_list)
#     tmp_df, result = store_storage(data, store_nbr, f_name)
#     o_df = o_df.append(tmp_df, ignore_index=True)

 67%|██████▋   | 30/45 [00:01<00:00, 17.44it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1471: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
100%|██████████| 45/45 [00:02<00:00, 17.69it/s]

In [42]:
# o_df.to_csv('store_units0_OLS_3차(p-value제거).csv', sep=',', index=None)

## Model

In [21]:
#item_nbr 기준으로 OLS 분류
ls_item_nbr = set(all_data_result.item_nbr)
i_df = pd.DataFrame()
i_df_out = pd.DataFrame()
for item_nbr in tqdm(ls_item_nbr):
    data = all_data_result[all_data_result['item_nbr'] == item_nbr]
    data = data[data['units'] > 0]
    tmp_df, result = item_storage(data, item_nbr, None)
    i_df = i_df.append(tmp_df, ignore_index=True)
    temp = erase_outlier_np(result, data)  #아웃라이어 제거
    i_df_out = i_df_out.append(temp, ignore_index=True)

  0%|          | 0/111 [00:00<?, ?it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:309: RuntimeWarning: invalid value encountered in sqrt
  return  self.results.resid / sigma / np.sqrt(1 - hii)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()
 85%|████████▍ | 94/111 [00:19<00:03,  4.79it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:309: RuntimeWarning: divide by zero encountered in true_divide
  return  self.results.resid / sigma / np.sqrt(1 - hii)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:403: RuntimeWarning: divide by zero encountered in true_divide
  cooks_d2 *= hii / (1 - hii)
100%|██████████| 111/111 [00:23<00:00,  4.79it/s]

In [22]:
i_df.to_csv('item_units0_OLS_1차.csv',sep=',', index=None )

In [23]:
#2차 _ 아웃라이어 제거
ls_item_nbr = set(all_data_result.item_nbr)
i_df = pd.DataFrame()
for item_nbr in tqdm(ls_item_nbr):
    data = i_df_out[i_df_out['item_nbr'] == item_nbr]
    data = data[data['units'] > 0]
    tmp_df, result = item_storage(data, item_nbr, None)
    i_df = i_df.append(tmp_df, ignore_index=True)

 91%|█████████ | 101/111 [00:13<00:01,  7.71it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/stats.py:1390: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  "anyway, n=%i" % int(n))
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1392: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - np.divide(self.nobs - self.k_constant, self.df_resid) * (1 - self.rsquared)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1392: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - np.divide(self.nobs - self.k_constant, self.df_resid) * (1 - self.rsquared)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1400: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1353: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/base/model.py:1118: RuntimeWarning: invalid value encountered in multiply
  cov_p = self.normalized_cov_params * scale
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
100%|██████████| 111/111 [00:14<00:00,  7.77it/s]

In [24]:
i_df.to_csv('item_units0_OLS_2차.csv',sep=',', index=None )

In [27]:
#store_nbr 기준으로 OLS 분류 - p-value 제거
ls_item_nbr = set(all_data_result.item_nbr)
i_o_df = pd.DataFrame()
for item_nbr in tqdm(ls_item_nbr):
    data = i_df_out[i_df_out['item_nbr'] == item_nbr]
    data = data[data['units'] > 0]
    i_f_list = item_formulaName(i_df, item_nbr)
    i_f_name = item_formulaList(i_f_list)
    tmp_df, result = item_storage(data, item_nbr, i_f_name)
    i_o_df = i_o_df.append(tmp_df, ignore_index=True)

 51%|█████▏    | 57/111 [00:03<00:03, 15.74it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1471: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
 91%|█████████ | 101/111 [00:05<00:00, 17.65it/s]/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/stats.py:1390: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  "anyway, n=%i" % int(n))
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1392: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - np.divide(self.nobs - self.k_constant, self.df_resid) * (1 - self.rsquared)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1392: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - np.divide(self.nobs - self.k_constant, self.df_resid) * (1 - self.rsquared)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1400: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1353: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/base/model.py:1118: RuntimeWarning: invalid value encountered in multiply
  cov_p = self.normalized_cov_params * scale
100%|██████████| 111/111 [00:06<00:00, 17.72it/s]

In [28]:
i_o_df.to_csv('item_units0_OLS_3차.csv',sep=',', index=None )

In [24]:
test = pd.read_csv('tae/test.csv')
weather = pd.read_csv('tae/weather_processed.csv')
key = pd.read_csv('tae/key.csv')
holidays = get_holidays("tae/walmart_holidays.txt")
holiday_names = get_holiday_names("tae/walmart_holiday_names.txt")
test_key = pd.merge(test, key, on=['store_nbr'], how='left')

test_merge =  pd.merge(test_key, weather, on=['date', 'station_nbr'], how='left')
test_gg = preprocess(test_merge)

In [129]:
aaa = test_gg[test_gg['holiday_name'] == 'ThanksgivingDay']
aaa.holiday_name

240648    ThanksgivingDay
240649    ThanksgivingDay
240650    ThanksgivingDay
240651    ThanksgivingDay
240652    ThanksgivingDay
240653    ThanksgivingDay
240654    ThanksgivingDay
240655    ThanksgivingDay
240656    ThanksgivingDay
240657    ThanksgivingDay
240658    ThanksgivingDay
240659    ThanksgivingDay
240660    ThanksgivingDay
240661    ThanksgivingDay
240662    ThanksgivingDay
240663    ThanksgivingDay
240664    ThanksgivingDay
240665    ThanksgivingDay
240666    ThanksgivingDay
240667    ThanksgivingDay
240668    ThanksgivingDay
240669    ThanksgivingDay
240670    ThanksgivingDay
240671    ThanksgivingDay
240672    ThanksgivingDay
240673    ThanksgivingDay
240674    ThanksgivingDay
240675    ThanksgivingDay
240676    ThanksgivingDay
240677    ThanksgivingDay
               ...
241728    ThanksgivingDay
241729    ThanksgivingDay
241730    ThanksgivingDay
241731    ThanksgivingDay
241732    ThanksgivingDay
241733    ThanksgivingDay
241734    ThanksgivingDay
241735    ThanksgivingDay
241736    ThanksgivingDay
241737    ThanksgivingDay
241738    ThanksgivingDay
241739    ThanksgivingDay
241740    ThanksgivingDay
241741    ThanksgivingDay
241742    ThanksgivingDay
241743    ThanksgivingDay
241744    ThanksgivingDay
241745    ThanksgivingDay
241746    ThanksgivingDay
241747    ThanksgivingDay
241748    ThanksgivingDay
241749    ThanksgivingDay
241750    ThanksgivingDay
241751    ThanksgivingDay
241752    ThanksgivingDay
241753    ThanksgivingDay
241754    ThanksgivingDay
241755    ThanksgivingDay
241756    ThanksgivingDay
241757    ThanksgivingDay
Name: holiday_name, Length: 1110, dtype: object

In [128]:
bbb = all_data_result[all_data_result['holiday_name'] == 'ThanksgivingDay']
bbb.holiday_name

36186      ThanksgivingDay
36187      ThanksgivingDay
36188      ThanksgivingDay
36189      ThanksgivingDay
36190      ThanksgivingDay
36191      ThanksgivingDay
36192      ThanksgivingDay
36193      ThanksgivingDay
36194      ThanksgivingDay
36195      ThanksgivingDay
36196      ThanksgivingDay
36197      ThanksgivingDay
36198      ThanksgivingDay
36199      ThanksgivingDay
36200      ThanksgivingDay
36201      ThanksgivingDay
36202      ThanksgivingDay
36203      ThanksgivingDay
36204      ThanksgivingDay
36205      ThanksgivingDay
36206      ThanksgivingDay
36207      ThanksgivingDay
36208      ThanksgivingDay
36209      ThanksgivingDay
36210      ThanksgivingDay
36211      ThanksgivingDay
36212      ThanksgivingDay
36213      ThanksgivingDay
36214      ThanksgivingDay
36215      ThanksgivingDay
                ...
4580163    ThanksgivingDay
4580164    ThanksgivingDay
4580165    ThanksgivingDay
4580166    ThanksgivingDay
4580167    ThanksgivingDay
4580168    ThanksgivingDay
4580169    ThanksgivingDay
4580170    ThanksgivingDay
4580171    ThanksgivingDay
4580172    ThanksgivingDay
4580173    ThanksgivingDay
4580174    ThanksgivingDay
4580175    ThanksgivingDay
4580176    ThanksgivingDay
4580177    ThanksgivingDay
4580178    ThanksgivingDay
4580179    ThanksgivingDay
4580180    ThanksgivingDay
4580181    ThanksgivingDay
4580182    ThanksgivingDay
4580183    ThanksgivingDay
4580184    ThanksgivingDay
4580185    ThanksgivingDay
4580186    ThanksgivingDay
4580187    ThanksgivingDay
4580188    ThanksgivingDay
4580189    ThanksgivingDay
4580190    ThanksgivingDay
4580191    ThanksgivingDay
4580192    ThanksgivingDay
Name: holiday_name, Length: 8880, dtype: object

In [90]:
model2 = sm.OLS.from_formula("units ~ weekday + is_weekend +"
                            "is_holiday +is_holiday_weekend + day +"
                            "year +"
                            "tmin + tavg  + wetbulb + heat+"
                            "cool + sunrise + sunset + snowfall + preciptotal + stnpressure+"
                            "sealevel + resultspeed + resultdir + avgspeed", data=all_data_result)
result = model2.fit()

num_attr = ['store_nbr', 'item_nbr', 'weekday', 'is_weekend', 
            'is_holiday', 'is_holiday_weekend',
            'day', 'year',
            'tmin', 'tavg',
            'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'snowfall',
            'preciptotal', 'stnpressure', 'sealevel', 'resultspeed',
            'resultdir', 'avgspeed']

test_predict = test_gg[num_attr]

test = result.predict(test_predict)